### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Tanaka925** [Tanaka925/furima-40189#20]
# URL
https://furima-40189.onrender.com/

# Basic認証のIDとパスワード
admin / 2222

# 出品者用のメールアドレスとパスワード
ado@ado / Furima0101

# 購入者用のメールアドレスとパスワード
ado2@ado / Furima0909

**Comment by motomuun** [comment]
@Tanaka925 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品編集機能の確認**

- [x] **ログイン状態の場合は、自身が出品した販売中商品の商品情報編集ページに遷移できること**
「編集」ボタンを押すと、エラーページに遷移します。編集ページに遷移できるように修正をお願いします。

- [x] **ログイン状態の場合でも、自身が出品した売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移すること**
売却済みの商品の商品情報編集ページへ遷移しようとすると、エラーページに遷移します。トップページに遷移するように修正をお願いします。



**商品購入機能の確認**

- [x] **郵便番号は、「3桁ハイフン4桁」の半角文字列のみ保存可能なこと**
3桁ハイフン4桁以上入力できてしまいます。具体的には「111-11111」のような文字列が入力可能です。
入力出来ないように修正をお願いします。

- [x] **電話番号は、10桁以上11桁以内の半角数値のみ保存可能なこと**
12桁以上の数値が入力可能です。11桁までしか入力できないように修正をお願いします。




修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Tanaka925** [comment]
ご確認いただきありがとうございます。
提出前に確認が不足しており、
失礼いたしました。

再度ご確認の程、よろしくお願いいたします。

**Comment by motomuun** [comment]
@Tanaka925 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by Tanaka925** [comment]
ありがとうございます！
今後ともよろしくお願いいたします。
